### ISSUE TITLE
Importing JSON file

### ISSUE THREAD

**Issue by StefTzor** [alexnoob/BasketBall-GM-Rosters#11]
Hi, I'm having a school project to create a simple App connected to a MySQL Database, the problem I have is that I'm trying to import the JSON file using the Table Data Import Wizard and I get this error "Can't analyze file. Please try to change encoding type. If that doesn't help, maybe the file is not: json, or the file is empty.". I'm kinda newbie here so sorry for any inconvenience.

**Comment by alexnoob** [comment]
Sadly I might be too much of a newbie too to help you :-( The file is encoded in UTF-8 if it could help, but I guess the issue might be related with the way the file is structured?!

**Comment by StefTzor** [comment]
I don't know much about JSON files and how they are structured, but is there any way to convert it to CSV or any other format? I've tried a script from GitHub but without much luck.
