### ISSUE TITLE
Houston Rockets logo should be replaced in 19-20

### ISSUE THREAD

**Issue by Nyargleblargle** [alexnoob/BasketBall-GM-Rosters#15]
The logo used in the 2019-20 file has apparently been retired. Perhaps replace it with [this](http://www.sportslogos.net/logos/view/23068302020/Houston_Rockets/2020/Primary_Logo)?

**Comment by alexnoob** [comment]
Thanks, I missed it! The logo will be updated in the 0.2 version of the roster
