### ISSUE TITLE
URL Redirect

### ISSUE THREAD

**Issue by nicidob** [alexnoob/BasketBall-GM-Rosters#16]
You pasted in the wrong URL on your “releases” post. You should follow the URL redirect to get
https://raw.githubusercontent.com/alexnoob/BasketBall-GM-Rosters/master/2019-20.NBA.Roster.json 

The one you pasted
https://github.com/alexnoob/BasketBall-GM-Rosters/raw/master/2019-20.NBA.Roster.json
Doesn’t work as-is

**Comment by alexnoob** [comment]
stupid me, it's fixed - thanks a lot!
