### ISSUE TITLE
This is Awesome!  Request 2000-2001 Year Roster?

### ISSUE THREAD

**Issue by lhaggarty** [alexnoob/BasketBall-GM-Rosters#17]
This is awesome!

Thanks so much for making this alexnoob.  I'm wondering if you, or someone else has created, or would consider creating a 2000-2001 roster for GM Basketball?

Regards,
Leon

**Comment by alexnoob** [comment]
Thanks for your really kind message! Regarding the 2000-2001 roster (and others), have a look here, you'll probably love it :) https://nicidob.github.io/rosters/
