### ISSUE TITLE
Player Overalls

### ISSUE THREAD

**Issue by ssf23** [alexnoob/BasketBall-GM-Rosters#22]
There is some issues with the player overalls. Kyrie is a 61 overall when I get into the game and Oladipo is in the upper 70s. How? Also, AD is apparently the best player in the league by 2 overalls and Giannis is only a 73 and Russ is only a 70. Also, Luka is apparently garbage. Were those glitches or mistakes? Because usually, it would be Kawhi, Harden and Giannis in the upper 70s and ppl like AD and Lebron right behind. This is with the newest November update.

**Comment by alexnoob** [comment]
You see fuzzed ratings, use God Mode to see the real ones. The top 4 players are currently:
James Harden
Paul George
Anthony Davis
Kawhi Leonard
LeBron James

Doncic will be a borderline top 15 player in the next update. His ratings were mostly based on the previous season. Maybe it's not enough, we'll see if he keeps his incredible season.

Oladipo is IMHO a much more complete and efficient player than Kyrie. Maybe the gap is too big, I don't know. I don't focus too much on overall, but rather on simulated stats
