### ISSUE TITLE
Bucks need rebalance

### ISSUE THREAD

**Issue by brickartist** [alexnoob/BasketBall-GM-Rosters#23]
I've been doing quite a bit of testing as part of patching the playoffs (8 and 7 seeds are upsetting way too frequently), and as part of this I've discovered that the Bucks always underperform relative to their real world counterparts in the regular season. Now this could be an issue with the game simulator, the roster, or perhaps both, but I'd thought I'd also post here to share my findings.

In my latest test of 72 seasons, the Bucks finish:
1st seed: 0 times
2nd seed: 1 time
3rd seed: 4 times
4th seed: 2 times
5th seed: 11 times
6th seed: 14 times
7th seed: 11 times
8th seed: 13 times

**Comment by alexnoob** [comment]
Hello, I'm aware of the issue. The Bucks have the best team rating of the East but don't perform well in the regular season. If you have suggestions on how to improve players ratings feel free to post them!

Edit: try this new version, Bucks should perform a tad better https://github.com/alexnoob/BasketBall-GM-Rosters/raw/master/2019-20.NBA.Roster.json

**Comment by brickartist** [comment]
thanks! ill run a bunch of sims tonight and post the results tomorrow

**Comment by brickartist** [comment]
and also let me know if there are any other teams' performances you'd like to see

**Comment by brickartist** [comment]
coming back to this - with 100 seasons with the latest roster:
1st seed: 4 times
2nd seed: 5 times
3rd seed: 9 times
4th seed: 5 times
5rh seed: 4 times
6th seed: 12 times
7th seed: 18 times
8th seed: 15 times

so it looks a little better
