### ISSUE TITLE
Nba teams Roster bug

### ISSUE THREAD

**Issue by ytlilpeteythebeast** [alexnoob/BasketBall-GM-Rosters#28]
the nba teams roster you made for some reason does not work and it keeps saying that the Imput is not an object is there something wrong with the roster or is that something on my part
![Screenshot 2021-01-04 at 11 34 38 AM](https://user-images.githubusercontent.com/68977501/103557312-fd74c200-4e80-11eb-8db1-6e589c82ea57.png)

**Comment by alexnoob** [comment]
no it's not here, if you want to use the roster go to https://play.basketball-gm.com/new_league then select "Upload League File" or "Enter League URL" under the Customize menu
