### ISSUE TITLE
prospects

### ISSUE THREAD

**Issue by PhonkGod666** [alexnoob/BasketBall-GM-Rosters#36]
can you add Nate Bittle? He was a top 10 recruit and McDonalds all American. If not no problem (Your rosters make this game dope keep up the good work broddie)

**Comment by alexnoob** [comment]
ok I'll add him in a future version, thanks for the sugestion!

**Comment by alexnoob** [comment]
I've just added him, he'll be available in the next version! Thanks again for the suggestion
