### ISSUE TITLE
Zach LaVine

### ISSUE THREAD

**Issue by ninjasean56** [alexnoob/BasketBall-GM-Rosters#37]
In all my sims, LaVine's efficiency is like 40/35/90 using the un-updated roster which his stats were 50/42/85. So, i think his new ratings should be kept the same except for:

Passing: Lower to 50 to keep the balance with the dribble/pass passing tendency stuff.
Dribbling: Raise to 72 to give better efficiency
Free Throw: lower to 65 to lower the FT%

His efficiency in this sim turned out to be
![image](https://user-images.githubusercontent.com/57674912/128102959-08a3c6dc-01a3-4781-aba7-6afc8a17be8a.png)

**Comment by alexnoob** [comment]
Thanks for your suggestions! I've updated his passing/dribbling ratings as suggested. You can check the updated roster.

Keep in mind the current roster starts *before* the 2022 season, so there is always a random player progression at the beginning of the season.


Regarding FT%: his 85% in 2021-21 equals to a FT rating of 67 (was 70). 65 FT rating is 84%, but randomness happens ingame :-)
