### ISSUE TITLE
Anthony Davis

### ISSUE THREAD

**Issue by AppleMane** [alexnoob/BasketBall-GM-Rosters#38]
It seems like Anthony Davis' numbers are broken, im not sure if it's just something on my end, but its bugging me nonetheless

![Screenshot_20210823-171542](https://user-images.githubusercontent.com/89425025/130526477-956aca94-5d54-4c8d-a9d9-04b8017f3eda.png)

**Comment by alexnoob** [comment]
You're right, thanks for the heads up! I've just fixed and updated the file. This bug on my side was also available on a few other players
