### ISSUE TITLE
Loading BY URL with VPN

### ISSUE THREAD

**Issue by radxrico** [alexnoob/BasketBall-GM-Rosters#41]
When using a VPN with certain links I keep getting the following error:

<img width="322" alt="image" src="https://user-images.githubusercontent.com/108306972/180657313-8ac13ab9-ebfe-43d5-97b3-da06c48655eb.png">

It works fine with github links, but dropbox, google so far it will say that. I'll have to disable my VPN wait for my regular connection, then load, then reapply my VPN, wait for that to connect again etc..

**Comment by alexnoob** [comment]
Hello, I just make roster, I'm not the dev of the game. You should post the issue in https://github.com/zengm-games/zengm
