### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by itzzr1l3y** [alexnoob/BasketBall-GM-Rosters#42]
is it okay if you can put Luke Travers on the Cleveland Cavaliers since he is contracted for them, but he is playing in Australia under contract by the cavs. So when u do, u can probably add an injury for Australia so u cant use him until the next season?

**Comment by alexnoob** [comment]
I'd love to but that means he'll use a roster spot... The game engine currently doesn't handle "draft & stash" players, although I'd love to see it added. I think leaving him as a FA right now is the least worst solution right now...
