### ISSUE TITLE
can u make a my career mode and make it so when u have a great game u can upgrade ur player

### ISSUE THREAD

**Issue by Fireboyg23** [alexnoob/BasketBall-GM-Rosters#43]
can you make a my career mode  on basketball gm and make it so when you have a great game you can upgrade your player

**Comment by alexnoob** [comment]
I'm just a roster maker, I don't develop the game. You should ask here https://github.com/zengm-games/zengm

**Comment by Fireboyg23** [comment]
ok then can u ask him

**Comment by alexnoob** [comment]
sorry not interested

**Comment by Fireboyg23** [comment]
Ok, no problem.

**Comment by Fireboyg23** [comment]
why is donovan mitchell overall low he average 31 he should be at least a
70
