### ISSUE TITLE
Dalton Knecht

### ISSUE THREAD

**Issue by josiahmendoza** [alexnoob/BasketBall-GM-Rosters#45]
![Capture](https://github.com/alexnoob/BasketBall-GM-Rosters/assets/38730384/e2ab19f6-15ba-484b-bff1-98c187ef505a)

NBA Draft Prospect Dalton Knecht is 31 for 2023-2024 Roster

**Comment by alexnoob** [comment]
Wow, thanks for the heads up! That's really the kind of stupid mistake I still make way too often. It will be fixed within the next hour!
