### ISSUE TITLE
The removed players roster doesn't work in import players

### ISSUE THREAD

**Issue by itzzr1l3y** [alexnoob/BasketBall-GM-Rosters#47]

**Comment by alexnoob** [comment]
I've got the same error message with all my custom rosters. I've just asked dumbmatter, I'll keep you in touch

**Comment by alexnoob** [comment]
Feedback from dumbmatter: not sure if he's gonna fix it, but if you create a league from a file and then export it, it will work. Is that workaround good enough from the time being?
