### ISSUE TITLE
roster has IT/etc. on Cleveland but missing Kyrie on Boston.

### ISSUE THREAD

**Issue by whoisearth** [alexnoob/BasketBall-GM-Rosters#7]

**Comment by whoisearth** [comment]
found him.  He's on the Atlanta Hawks.  They don't deserve him.

**Comment by alexnoob** [comment]
it's fixed - the released version was fine

**Comment by NBALIVE18** [comment]
I can you please update kyrie real team

**Comment by alexnoob** [comment]
download the release - he's on the right team
